### ISSUE TITLE
Project not even runable

### ISSUE THREAD

**Issue by xHatti** [joinfaces/joinfaces-maven-jar-example#293]
Project is not buildable due to errors. Example webpage mentioned on description is not working..

Was looking if changing the primefaces theme will apply on this project.. In my project it wont and i dont know why..

**Comment by Betlista** [comment]
I can build version 4.1.1, but it is not runnable.

On http://localhost:8080/starter.jsf I'm getting:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Dec 25 12:05:41 CET 2019
There was an unexpected error (type=Internal Server Error, status=500).
/file:/C:/betlista/Git/GitHub.com/joinfaces-maven-jar-example/target/joinfaces-example-4.1.1.jar!/META-INF/resources/starter.xhtml @27,79 rendered="#{sec:isFullyAuthenticated()}" Function [sec:isFullyAuthenticated] not found
```

**Comment by ramsonline** [comment]
i have the same problem.

i just followed the Readme and ran into an error. Is there a known way to resolve this ?

**Comment by hotwind2015** [comment]
1、download xalan packages from apache and install into local maven reps
2、modify src\main\resources\META-INF\resources\starter.xhtml
change xmlns:sec="http://www.springframework.org/security/tags" to xmlns:sec="https://joinfaces.org/security"
3、modify src\main\java\org\joinfaces\example\view\JoinFacesStarterService.java 
change the createModel() method ,  replace "joinfaces-dependencies" to "joinfaces"

**Comment by hotwind2015** [comment]
> Project is not buildable due to errors. Example webpage mentioned on description is not working..
> 
> Was looking if changing the primefaces theme will apply on this project.. In my project it wont and i dont know why..

1、download xalan packages from apache and install into local maven reps
2、modify src\main\resources\META-INF\resources\starter.xhtml
change xmlns:sec="http://www.springframework.org/security/tags" to xmlns:sec="https://joinfaces.org/security"
3、modify src\main\java\org\joinfaces\example\view\JoinFacesStarterService.java
change the createModel() method , replace "joinfaces-dependencies" to "joinfaces"

**Comment by hotwind2015** [comment]
> i have the same problem.
> 
> i just followed the Readme and ran into an error. Is there a known way to resolve this ?
> 
> This is what the Log shows :
> 
> ```
> 2020-04-06 13:56:51.378  INFO 16288 --- [nio-8080-exec-1] o.o.r.param.DefaultParameterValueStore   : Loaded [1] org.ocpsoft.rewrite.spi.GlobalParameterProvider [org.ocpsoft.rewrite.instance.WildcardParameterProvider<0>]
> 2020-04-06 13:56:51.987 ERROR 16288 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[FacesServlet]         : Servlet.service() for servlet [FacesServlet] in context with path [] threw exception [/file:/C:/Users/proeppk/lokaler%20Eclipse%20Workspace/joinfaces-maven-jar-example/target/joinfaces-example-4.1.1.jar!/META-INF/resources/starter.xhtml @27,79 rendered="#{sec:isFullyAuthenticated()}" Function [sec:isFullyAuthenticated] not found] with root cause
> 
> javax.el.ELException: Function [sec:isFullyAuthenticated] not found
>         at org.apache.el.lang.ExpressionBuilder.visit(ExpressionBuilder.java:219) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
>         at org.apache.el.parser.SimpleNode.accept(SimpleNode.java:142) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
>         at org.apache.el.lang.ExpressionBuilder.prepare(ExpressionBuilder.java:161) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
>         at org.apache.el.lang.ExpressionBuilder.build(ExpressionBuilder.java:179) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
>         at org.apache.el.lang.ExpressionBuilder.createValueExpression(ExpressionBuilder.java:242) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
>         at org.apache.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:67) ~[tomcat-embed-el-9.0.27.jar!/:9.0.27]
> ```

1、download xalan packages from apache and install into local maven reps
2、modify src\main\resources\META-INF\resources\starter.xhtml
change xmlns:sec="http://www.springframework.org/security/tags" to xmlns:sec="https://joinfaces.org/security"
3、modify src\main\java\org\joinfaces\example\view\JoinFacesStarterService.java
change the createModel() method , replace "joinfaces-dependencies" to "joinfaces"

**Comment by hotwind2015** [comment]
modify src\main\java\org\joinfaces\example\view\JoinFacesStarterService.java
change the createModel() method , replace "http://" to "https://"

modify pom.xml , replace spring repository "http://" to "https://"

**Comment by Betlista** [comment]
@hotwind2015 you do not need to add same reply to every comment ;-)

Feel free to create pull request (PR) with your changes.
