### ISSUE TITLE
Can't build project because of test errors

### ISSUE THREAD

**Issue by malk42** [joinfaces/joinfaces-maven-jar-example#411]
Hello,

i checked it out and also have lombok installed. But I get an erro in the  pom.xml

> Plugin execution not covered by lifecycle configuration: org.joinfaces:joinfaces-maven-plugin:4.4.2:classpath-scan (execution: default, phase: process-classes)	pom.xml	/joinfaces-maven-jar-example	line 273

When I build it with `mvn clean install` i get errors:

> [ERROR] Errors: 
> [ERROR]   StarterPageIT.clickAdminfaces:186 » ElementNotInteractable Element <span class...
> [ERROR]   StarterPageIT.clickAngularfaces:141 » ElementNotInteractable Element <span cla...
> [ERROR]   StarterPageIT.clickMyfaces:66 » ElementNotInteractable Element <div id="tabVie...
> [ERROR]   StarterPageIT.clickOmnifaces3:216 » ElementNotInteractable Element <span class...
> [ERROR]   StarterPageIT.clickPrimefaces:96 » ElementNotInteractable Element <span class=...
> [ERROR]   StarterPageIT.clickRichfaces:156 » ElementNotInteractable Element <span class=...
> [ERROR]   StarterPageIT.clickSecurity:81 » ElementNotInteractable Element <span class="u...
> [INFO] 
> [ERROR] Tests run: 33, Failures: 0, Errors: 7, Skipped: 0

from the logs:

`<testcase name="clickOmnifaces1" classname="org.joinfaces.example.view.StarterPageIT" time="0.564">
<error message="Element <span class="ui-chkbox-icon ui-icon ui-icon-blank ui-c"> could not be scrolled into view Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'myHostPC', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-65-generic', java.version: '11.0.10' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 85.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210118153634, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 25975, moz:profile: /tmp/rust_mozprofile0BxsvW, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.4.0-65-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify} Session ID: b8147fd9-3839-4fe7-b535-4cfd483ef581" type="org.openqa.selenium.ElementNotInteractableException">
<![CDATA[ org.openqa.selenium.ElementNotInteractableException: Element <span class="ui-chkbox-icon ui-icon ui-icon-blank ui-c"> could not be scrolled into view Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'myHostPC', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-65-generic', java.version: '11.0.10' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 85.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210118153634, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 25975, moz:profile: /tmp/rust_mozprofile0BxsvW, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 5.4.0-65-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify} Session ID: b8147fd9-3839-4fe7-b535-4cfd483ef581 at org.joinfaces.example.view.StarterPageIT.clickOmnifaces1(StarterPageIT.java:201) ]]>
</error>`

**Comment by timcolson** [comment]
I had test errors on macOS. I had to install Firefox. After doing that, Firefox popped up, lots of automatic testing seems to have worked, but 10 errors on StarterPageIT.java

Seems related, yes?

FYI - I tried skipping the tests, build succeeded, but running it fails to startup the app context.

```
2021-04-11 20:16:41.212  INFO 7867 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-11 20:16:41.222 ERROR 7867 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application' defined in BeanDefinition defined in class path resource [org/joinfaces/autoconfigure/javaxfaces/JsfBeansAutoConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "cause" is null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:610) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton
```

```
20:11:55.336 [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   StarterPageIT.clickAngularfaces:141 » ElementNotInteractable Element <div clas...
[ERROR]   StarterPageIT.clickBootsfaces:111 » ElementNotInteractable Element <div class=...
[ERROR]   StarterPageIT.clickButterfaces:126 » ElementNotInteractable Element <div class...
[ERROR]   StarterPageIT.clickIcefaces:171 » ElementNotInteractable Element <div class="u...
[ERROR]   StarterPageIT.clickMyfaces:66 » ElementNotInteractable Element <div id="tabVie...
[ERROR]   StarterPageIT.clickOmnifaces1:201 » ElementNotInteractable Element <div class=...
[ERROR]   StarterPageIT.clickPrimefaces:96 » ElementNotInteractable Element <div class="...
[ERROR]   StarterPageIT.clickRichfaces:156 » ElementNotInteractable Element <div class="...
[ERROR]   StarterPageIT.clickSecurity:81 » ElementNotInteractable Element <div class="ui...
[ERROR]   StarterPageIT.clickWeld:246 » ElementNotInteractable Element <div class="ui-ch...
[INFO]
[ERROR] Tests run: 33, Failures: 0, Errors: 10, Skipped: 0
[INFO]
```

```
-------------------------------------------------------------------------------
Test set: org.joinfaces.example.view.StarterPageIT
-------------------------------------------------------------------------------
Tests run: 15, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 8.555 s <<< FAILURE! - in org.joinfaces.example.view.StarterPageIT
clickWeld  Time elapsed: 0.311 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickWeld(StarterPageIT.java:246)

clickOmnifaces1  Time elapsed: 0.622 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickOmnifaces1(StarterPageIT.java:201)

clickIcefaces  Time elapsed: 0.234 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickIcefaces(StarterPageIT.java:171)

clickAngularfaces  Time elapsed: 0.229 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickAngularfaces(StarterPageIT.java:141)

clickRichfaces  Time elapsed: 0.23 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickRichfaces(StarterPageIT.java:156)

clickBootsfaces  Time elapsed: 0.314 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickBootsfaces(StarterPageIT.java:111)

clickButterfaces  Time elapsed: 0.352 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickButterfaces(StarterPageIT.java:126)

clickSecurity  Time elapsed: 0.375 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickSecurity(StarterPageIT.java:81)

clickPrimefaces  Time elapsed: 0.235 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickPrimefaces(StarterPageIT.java:96)

clickMyfaces  Time elapsed: 0.225 s  <<< ERROR!
org.openqa.selenium.ElementNotInteractableException: 
Element <div id="tabView:myfaces" class="ui-radiobutton ui-widget"> could not be scrolled into view
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DarkStar.lan', ip: 'fe80:0:0:0:8c5:466a:34ac:b8b8%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '11.2.3', java.version: '16'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 87.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210318103112, moz:geckodriverVersion: 0.29.0, moz:headless: false, moz:processID: 7605, moz:profile: /var/folders/bf/8s00wdb17_9..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.3.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ccdb415b-24d9-6343-ad43-e27ae3663b23
	at org.joinfaces.example.view.StarterPageIT.clickMyfaces(StarterPageIT.java:66)
```
